from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsLayerTreeGroup,
)

from pathlib import Path


# ---------------------------------
# Configuration
# ---------------------------------

BASE = Path(
    "/home/jasvir/Projects/HRTK-GIS-Bridge"
)


GPKG = str(
    BASE /
    "output/HRTK_Land_Data.gpkg"
)


OUTPUT = str(
    BASE /
    "qgis/HRTK_Land_Project.qgz"
)



PROJECT = QgsProject.instance()



# ---------------------------------
# Reset project
# ---------------------------------

PROJECT.clear()

root = PROJECT.layerTreeRoot()



# ---------------------------------
# Create group
# ---------------------------------

group = root.addGroup(
    "HRTK Land Intelligence"
)



# ---------------------------------
# Load final GIS layer only
#
# Generated by:
# create_clean_parcel_land_view.py
#
# Contains:
# - geometry
# - parcel information
# - khewat number
# - ownership
# - owner details
# ---------------------------------

uri = (
    f"{GPKG}|layername=parcel_land_view_clean"
)


land_layer = QgsVectorLayer(
    uri,
    "Land Parcels",
    "ogr"
)



if not land_layer.isValid():

    raise Exception(
        "Failed loading parcel_land_view_clean"
    )



PROJECT.addMapLayer(
    land_layer,
    False
)


group.addLayer(
    land_layer
)



print(
    "Loaded: Land Parcels"
)



# ---------------------------------
# Save project
# ---------------------------------

PROJECT.write(
    OUTPUT
)


print()
print(
    "Created:",
    OUTPUT
)